[project]
name = "sum-sines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "marimo[recommended]>=0.13.15",
    "pandas>=2.3.0",
]
